#!/usr/bin/env python

import os.path
import sys
from subprocess import Popen, PIPE
import py_compile

BASE_DIR = os.getcwd()
code_result = 0

# pushing of non-compile projects restriction.
for root, dirs, files in os.walk(BASE_DIR, topdown=True):
    if root.find('env') == -1 and root.find('__pycache__') == -1 and root.find('.git') == -1 and root.find(
            '.idea') == -1:
        for name in files:
            if name.find('.py') != -1:
                try:
                    py_compile.compile(os.path.join(root, name), doraise=True)
                except py_compile.PyCompileError as err:
                    print('One or more files are not compiling.')
                    print(err.exc_value)
                    code_result += 1

for file in os.listdir(os.path.join(BASE_DIR, '__pycache__')):
    os.remove(os.path.join(BASE_DIR, '__pycache__', file))


# pushing to master branch restriction.
def runBash(command):
    process = Popen(command, shell=True, stdout=PIPE)
    out = process.stdout.read().strip()
    return out


if str(runBash('git symbolic-ref HEAD')).find("master") != -1:
    print("You are not allowed commit changes in master branch")
    code_result = 1

exit(code_result)


